
# This file is used to configure your Supabase project.
# For the full list of configuration options, see:
# https://supabase.com/docs/reference/api/supabase-config

project_id = "yfzitleumutyjktcpyac"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_expiry = 604800
enable_signup = true

[realtime]
enabled = true

[storage]
# Create freelancer-images bucket
[[storage.buckets]]
name = "freelancer-images"
public = true
allowed_mime_types = ["image/png", "image/jpeg", "image/gif", "image/webp", "image/svg+xml"]
file_size_limit = "5242880"

[[storage.buckets.policies]]
name = "Allow authenticated users to upload their own images"
definition.role = "authenticated"
definition.operations = ["SELECT", "INSERT", "UPDATE", "DELETE"]
definition.expression = '''
  (bucket_id = 'freelancer-images' AND 
    (storage.foldername(name))[1] = auth.uid()::text)
'''

[[storage.buckets]]
name = "portfolio-images"
public = true
allowed_mime_types = ["image/png", "image/jpeg", "image/gif", "image/webp", "image/svg+xml"]
file_size_limit = "10485760"

[[storage.buckets.policies]]
name = "Allow authenticated users to upload their own portfolio images"
definition.role = "authenticated"
definition.operations = ["SELECT", "INSERT", "UPDATE", "DELETE"]
definition.expression = '''
  (bucket_id = 'portfolio-images' AND 
    (storage.foldername(name))[1] = auth.uid()::text)
'''

[[storage.buckets.policies]]
name = "Allow public to view all portfolio images"
definition.role = "anon"
definition.operations = ["SELECT"]
definition.expression = '''
  bucket_id = 'portfolio-images'
'''
