// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfzitleumutyjktcpyac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmeml0bGV1bXV0eWprdGNweWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTkzNzYsImV4cCI6MjA2MTkzNTM3Nn0.MKgWio8uliATmh1TnmevdmR5A45hLEaG9u1OY2ymXw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);